### PR TITLE
Add document introducing JADN

### PR DESCRIPTION
**Pull request by dlemire60**
Portion of response to @sparrell suggestions to add JADN material to TC Ops and OpenC2.org. This PR:
 - adds a JADN introductory document to the repository (with two associated images)
 - adds the document to the "What's Here" list in README.md

After this PR is approved and merged, the (draft) JADN FAQs for the OpenC2.org website should be updated to include it.

### CODE REVIEW

**Comment by davaya** [comment]
I approve.

**Review by davaya — APPROVED** [review]

**Comment by dlemire60** [comment]
@davaya's PR to this document added a definition for a Logical Model (which is good), with a link to the W3C's definition of OWL, which doesn't seem as helpful.  I did a little digging and found this TIBCO page on logical models:  https://www.tibco.com/reference-center/what-is-a-logical-data-model, which is pretty of close. I'm also wondering if we should add either words or a graphic to more clearly illustrate the Logical / Information / Data / JADN model relationships. The current wording (lines 68-74 of the new document) doesn't feel quite complete to me.

**Comment by davaya** [comment]
"Why not OWL" distinguishes between logical and information models, highlighting their differences.  Just as JADN is not an ontology language, OWL is not an IM language.  Both have their place.

The TIBCO page illustrates the database oriented use of "logical data models", which is distinct from logical knowledge models.  The Lombardi scholarly paper on IM, though quite theoretical, begins with a readable discussion of how the term "information" is highly overloaded.  "Logical" is similarly overloaded; JADN cannot declare that one interpretation is correct or preferred, it can only describe how IMs can be derived from either.

**Comment by dlemire60** [comment]
This PR was approved to be merged at the 14 December 2022 working meeting.

**Pull request merged**
